# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[staging.deploy.parameters]
[staging.global.parameters]
stack_name = "sam-fcm-worker"
resolve_s3 = false
s3_prefix = "sam-fcm-worker"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vu5vqppvrosl"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []